repos:
  # standard handling space/newline
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^(src/|include/)

      - id: end-of-file-fixer
        files: ^(src/|include/)

  # clang-format (auto format)
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        args: ["--style=file"]
        files: ^(src/|include/)
        exclude: ^Libraries/

  # cppcheck (include misra-c)
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        name: Cppcheck MISRA
        args:
          - --enable=all
          - --error-exitcode=1
          - --addon=tools/cppcheck_config/misra.json
        pass_filenames: true
        additional_dependencies: []
        verbose: true
        files: ^(src/|include/)
        log_file: tools/cppcheck_config/cppcheck_report.txt

  # check git convention
  - repo: local
    hooks:
      # check branch naming convention
      - id: check-branch-naming
        name: Check Branch Naming Convention
        entry: python tools/git_hooks/check_branch_naming.py
        language: system
        stages: [pre-commit]
        always_run: true
        pass_filenames: false

      # check commit message convention
      - id: check-commit-message
        name: Check Commit Message Convention
        entry: python tools/git_hooks/check_commit_message.py
        language: system
        stages: [commit-msg]
        always_run: true
        pass_filenames: true
