repos:
  # 기본적인 공백/줄바꿈 처리
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # clang-format (자동 포맷)
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        args: ["--style=file"]
        files: \.(c|h|cpp|hpp)$

  # cppcheck (misra-c 반영)
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:

      - id: cppcheck
        name: Cppcheck MISRA
        args:
          - --enable=all
          - --error-exitcode=1
          - --addon=tools/cppcheck_config/misra.json
        pass_filenames: false
        additional_dependencies: []
        verbose: true
        log_file: tools/cppcheck_config/cppcheck_report.txt
