name: Code Convention Check

on: [push, pull_request]

jobs:
  code-convention:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run code convention check
        run: bash tools/check_code_convention.sh

      - name: Read summary (for Slack)
        id: read-summary
        if: failure()
        run: |
          if [ -f tools/code-convention-summary.txt ]; then
            SUMMARY=$(cat tools/code-convention-summary.txt | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
            echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
          else
            echo "summary=No summary file found." >> $GITHUB_OUTPUT
          fi

      - name: Upload Code Convention Report (on failure only)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: code-convention-report
          path: |
            tools/code-convention-report.txt
            tools/code-convention-summary.txt

      - name: Slack notification (on failure)
  if: failure()
  uses: slackapi/slack-github-action@v1.24.0
  with:
    payload: |
      {
        "text": "*🚨 Code Convention Check Failed!*\n\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Author:* ${{ github.actor }}\n*Summary:*\n${{ steps.read-summary.outputs.summary }}"
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}



